# Site settings
title: Yilin Yang Blog
SEOTitle: Yilin Yang
header-img: img/CE45DFAA-AF7F-4E6E-82B5-799829044D32.jpeg
email: yilinyang0619@gmail.com
phone: (615)3195836
description: "Every failure is leading towards success."
url: "http://yy-ds.github.io"          # your host, for absolute URL
github_repo: "https://github.com/yy-ds/yy-ds.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "In the end, we are all alone"
sidebar-avatar: /img/D9B9F938-D658-4906-8661-F77D6992758B.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`





# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




